{% set name = "mo-dots" %}
{% set version = "9.562.24075" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-dots-{{ version }}.tar.gz
  sha256: 6634193b0e5affc2521cdc816325a47d37889588150402d0cb60c212f8056208

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - mo-future ==7.546.24057
    - mo-imports ==7.546.24057
    - python >=2.7

test:
  imports:
    - mo_dots
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-dots
  summary: More Dots! Dot-access to Python dicts like Javascript
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
